### ISSUE TITLE
Allow arbitrary "setup commands" instead of sourcing bash profile

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/quickterm#21]
Instead of having an option to source the bash profile, add arbitrary commands that are run before (and after) each command.

```
commandConfiguration:
  executeBefore:
    - source ~/.bash_profile
    - set -e
  executeAfter:
    - custom_cleanup
```
